# print ('WELCOME TO UNIQUE BANK OF WORLD')
# print ('SWIPE UP YOUR CARD ')
# a= "Y"
# pin_no = int(input('enter your no '))
# card_no = int(input('enter your no  '))
# balance_1 = 10000
# if card_no == 9999 and pin_no == 1010:
#     while a == "Y":
#         print('choose your transaction')
#         print (""" 
#         1.BALANCE CHECK
#         2. DEPOSIT
#         3. WITHDRAWAL
#         4. PIN CHANGE""")
#         user_choice = (input('enetr your choice :'))
#         if user_choice == '1':
#             print(balance_1)
#         elif user_choice == '2':
#             deposit = int(input('enter your amount'))
#             balance = deposit + balance_1
#             print (balance , 'your final balance ')
#         elif user_choice == '3':
#             withdrawal = int(input('enter your amount '))
#             balance = balance_1 - withdrawal
#             print(balance)
#         elif user_choice == '4':
#             pin = int(input('enter your pin'))
#             print (pin)
            
#         a == input('do you want to continue ?(y/n)')
#         print('exit') 
#     else:
#         print('exit')
        
# else:
#     print('wrong password')
    # if a == input('DO YOU WANT TO CONTINUE ? (Y/N)')
    # print ('exit')

    
            

# else:
#     print('wrong password')
    # a= input('DO YOU WANT TO CONTINUE ? (Y/N)')
    # print ('exit')
            
                
        
                
            
            

# while a  == "Y":
#     product = int(input('enter your prouduct'))
#     comissionvalue = float(input('what is the comission'))
    
#     comission= product * comissionvalue
#     print ('the comission is', comission)
    
#     a= input('DO YOU WANT TO CONTINUE ?(Y/N)').upper()
# print('exit')

# QUESTION OF MERAKI ,,,LIST
# Q2
# number = (50,40,70,23,56,12,5,10,7)
# count = 0 
# for i in number:
#     if i >20 and i<40 :
#         count+=1
# print(count)

# Q3

# a= 20
# while a>-20:
#     print(a)
#     a=a-1
    
# a=[1,2]
# for i in a:
#     print(i)
#     a.append(i)

number = [21,23,45,65,21,21,3,34]

for i in number:
    